# Definisikan named volume untuk persistensi data
volumes:
  postgres-data:
    driver: local

# Definisikan network kustom agar container bisa berkomunikasi
networks:
  app-network:
    driver: bridge

services:

  go-backend:
    container_name: go-app
    build:
      context: .
      dockerfile: Dockerfile.app
    # Format: <region>-docker.pkg.dev/<project-id>/<repo-name>/<image-name>:<tag>
    image: asia-southeast2-docker.pkg.dev/your-gcp-project-id/my-go-backend/my-go-service:latest
    restart: always
    ports:
      - "80:8080"
    environment:
      # Variabel untuk koneksi database (dibaca dari .env)
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

      # Variabel untuk aplikasi (dibaca dari .env)
      APP_PORT: ${APP_PORT}
      GIN_MODE: "release"
      
      # Variabel untuk oAuth dan JWT (dibaca dari .env)
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      SESSION_SECRET: ${SESSION_SECRET}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL}
    depends_on:
      - postgres_db
    networks:
      - app-network

  postgres_db:
    container_name: budgeting-BE
    build: 
      context: . 
      dockerfile: Dockerfile.postgres
    restart: always 
    # Variabel lingkungan untuk konfigurasi database
    # Nilai-nilai ini akan dimuat dari file .env secara otomatis
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    # Map port 5432 di host ke port 5432 di dalam kontainer
    ports:
      - "15001:5432"

    # Definisikan volume untuk menyimpan data database secara persisten
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network


